export enum ErrorCodes {
	// Request Errors
	BAD_REQUEST = "BAD_REQUEST",
	VALIDATION_ERROR = "VALIDATION_ERROR",

	// Server Errors
	INTERNAL_ERROR = "INTERNAL_ERROR",

	// Auth Errors
	UNAUTHORIZED = "UNAUTHORIZED",
	INVALID_TOKEN = "INVALID_TOKEN",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	VERIFICATION_TOKEN_EXPIRED = "VERIFICATION_TOKEN_EXPIRED",
	RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED",
	FORBIDDEN = "FORBIDDEN",
	ORGANIZATION_DOMAIN_MISMATCH = "ORGANIZATION_DOMAIN_MISMATCH",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED",
	REGISTRATION_UNSUCESSFUL = "REGISTRATION_UNSUCESSFUL",
	RESEND_VERIFICATION_LINK_FAILURE = "RESEND_VERIFICATION_LINK_FAILURE",

	// User Errors
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

	// Item-related (Lost & Found domain)
	ITEM_NOT_FOUND = "ITEM_NOT_FOUND",
	ITEM_ALREADY_CLAIMED = "ITEM_ALREADY_CLAIMED",
}
