export const locations: string[] = [
	"Main Gate",
	"Administration Block",
	"Central Library",
	"Computer Centre (CCC)",
	"Student Activity Centre (SAC)",
	"Auditorium",
	"Open Air Theatre",
	"Sports Complex / Stadium / Main Playground",
	"Health Centre",
	"Main Canteen / Food Court",
	"Cooperative Store / Shopping Complex",
	"SBI Bank and ATM",
	"Post Office",
	"Bus Stop (Campus)",
	"Central Workshop",
	"Training & Placement Cell",
	"Guest House",
	"Boys Hostels",
	"Ladies Hostels / MHL",
	"Architecture Department",
	"Computer Science & Engineering Department",
	"Electronics & Communication Engineering Department",
	"Electrical & Electronics Engineering Department",
	"Mechanical Engineering Department",
	"Civil Engineering Department",
];
